# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Song.create(name: '420', abbreviation: '420', length: 4.4)
Song.create(name: '1759', abbreviation: '1759', length: 9.7)
Song.create(name: '12 Wolves', abbreviation: '', length: 11.5)
Song.create(name: 'Acadian Driftwood', abbreviation: '', length: 8.5)
Song.create(name: 'All Alone', abbreviation: '', length: 8.9)
Song.create(name: 'All That\'s Dead', abbreviation: '', length: 2.7)
Song.create(name: 'All Things Must Pass', abbreviation: '', length: 7.3)
Song.create(name: 'Any Road', abbreviation: '', length: 4.6)
Song.create(name: 'Been Down That Road', abbreviation: '', length: 5.7)
Song.create(name: 'Berkeley Flash', abbreviation: '', length: 9)
Song.create(name: 'Bird in a House', abbreviation: '', length: 7.6)
Song.create(name: 'Birds of America', abbreviation: '', length: 13.4)
Song.create(name: 'Black Bear', abbreviation: '', length: 11.7)
Song.create(name: 'Black Elk Speaks', abbreviation: '', length: 6.7)
Song.create(name: 'Blazin\' a Trail', abbreviation: '', length: 5)
Song.create(name: 'Bluegrass Breakdown', abbreviation: '', length: 5.6)
Song.create(name: 'Bowling Green', abbreviation: '', length: 3.3)
Song.create(name: 'Bread and Water', abbreviation: '', length: 4.5)
Song.create(name: 'Bringin\' My Baby Back Home', abbreviation: '', length: 5.2)
Song.create(name: 'Brown Co Breakdown', abbreviation: '', length: 3.4)
Song.create(name: 'Butterfly and the Tree', abbreviation: '', length: 7.2)
Song.create(name: 'Came Up Smilin', abbreviation: '', length: 6.2)
Song.create(name: 'Captain Nowhere', abbreviation: '', length: 10)
Song.create(name: 'Carrying Coal to Newcastle', abbreviation: '', length: 7.6)
Song.create(name: 'Catfish John', abbreviation: '', length: 7.6)
Song.create(name: 'Chains', abbreviation: '', length: 5.4)
Song.create(name: 'Cold Water', abbreviation: '', length: 4.5)
Song.create(name: 'Colorado', abbreviation: '', length: 9.3)
Song.create(name: 'Congoman Chant', abbreviation: '', length: 12.5)
Song.create(name: 'Crazy Fingers', abbreviation: '', length: 9.3)
Song.create(name: 'Crossing the Gap', abbreviation: '', length: 4.4)
Song.create(name: 'Cuckoo, The', abbreviation: '', length: 8.5)
Song.create(name: 'Cuckoo\'s Medley, The', abbreviation: '', length: 10.3)
Song.create(name: 'Daddy-O', abbreviation: '', length: 3.8)
Song.create(name: 'Dance Around Molly>Dandelion Wine', abbreviation: 'DAM>DW', length: 7.7)
Song.create(name: 'Dance Around Molly', abbreviation: '', length: 2.6)
Song.create(name: 'Dandelion Wine', abbreviation: '', length: 5)
Song.create(name: 'Day on the Sand', abbreviation: '', length: 4.5)
Song.create(name: 'Dies Irae', abbreviation: '', length: 1.6)
Song.create(name: 'Donkey for Sale', abbreviation: '', length: 9.2)
Song.create(name: 'Dover to Dunkirk', abbreviation: '', length: 7)
Song.create(name: 'Drag Him Down', abbreviation: '', length: 6.1)
Song.create(name: 'Duncan and Brady', abbreviation: '', length: 6.1)
Song.create(name: 'El Cumbanchero', abbreviation: '', length: 6.7)
Song.create(name: 'Elko', abbreviation: '', length: 9.3)
Song.create(name: 'Everything Comes Together', abbreviation: '', length: 8.2)
Song.create(name: 'Face with a Hole', abbreviation: '', length: 8.2)
Song.create(name: 'Fairwell to Isinglass', abbreviation: '', length: 4.6)
Song.create(name: 'Fiddlee', abbreviation: '', length: 6)
Song.create(name: 'Fisherman\'s Blues', abbreviation: '', length: 6.9)
Song.create(name: 'Flower Between the Stones', abbreviation: '', length: 5.8)
Song.create(name: 'For Love', abbreviation: '', length: 7.3)
Song.create(name: 'Forecast, The', abbreviation: '', length: 10.3)
Song.create(name: 'Game Band Strut', abbreviation: '', length: 5)
Song.create(name: 'Genesis', abbreviation: '', length: 9)
Song.create(name: 'Give that Boy a Hand', abbreviation: '', length: 4.8)
Song.create(name: 'Goat', abbreviation: '', length: 11)
Song.create(name: 'Gold Rush', abbreviation: '', length: 6.4)
Song.create(name: 'Gone to the Feilds', abbreviation: '', length: 6)
Song.create(name: 'Good Life, The', abbreviation: '', length: 6.7)
Song.create(name: 'Grandfather Mountain', abbreviation: '', length: 12)
Song.create(name: 'Hangtown Ball', abbreviation: '', length: 10.1)
Song.create(name: 'Happy Song', abbreviation: '', length: 3.9)
Song.create(name: 'Hard Livin', abbreviation: '', length: 9.6)
Song.create(name: 'Harvest Moon', abbreviation: '', length: 8.6)
Song.create(name: 'Head', abbreviation: '', length: 15.2)
Song.create(name: 'Hot \'Lanta', abbreviation: '', length: 7.3)
Song.create(name: 'Hunting Song, The', abbreviation: '', length: 11.3)
Song.create(name: 'I Ain\'t Got No Home', abbreviation: '', length: 7.3)
Song.create(name: 'If You Will Be My Lady', abbreviation: '', length: 5)
Song.create(name: 'In Paradisum', abbreviation: '', length: 4.5)
Song.create(name: 'In the Basement', abbreviation: '', length: 5.4)
Song.create(name: 'Introit', abbreviation: '', length: 2.6)
Song.create(name: 'Jerusalem Ridge', abbreviation: '', length: 7.8)
Song.create(name: 'Judy Judy Judy', abbreviation: '', length: 6.1)
Song.create(name: 'Jupiter and the 119', abbreviation: '', length: 7.9)
Song.create(name: 'Just So You Know', abbreviation: '', length: 7.7)
Song.create(name: 'Keep Movin\' On', abbreviation: '', length: 7.5)
Song.create(name: 'Lacrimosa', abbreviation: '', length: 2.6)
Song.create(name: 'Last of the Outlaws', abbreviation: '', length: 7.8)
Song.create(name: 'Like a Buddha', abbreviation: '', length: 13.9)
Song.create(name: 'Little Bit O\' Me', abbreviation: '', length: 7.9)
Song.create(name: 'Little Rabbit', abbreviation: '', length: 6.7)
Song.create(name: 'Lois Ann', abbreviation: '', length: 4)
Song.create(name: 'Lonecroft Farewell', abbreviation: '', length: 7.5)
Song.create(name: 'Lonecroft Ramble', abbreviation: '', length: 4)
Song.create(name: 'Log Black Veil', abbreviation: '', length: 10.4)
Song.create(name: 'Long Walk Home', abbreviation: '', length: 5.4)
Song.create(name: 'Long Way to Go', abbreviation: '', length: 6.5)
Song.create(name: 'Lordy, Lordy', abbreviation: '', length: 4.5)
Song.create(name: 'Lovin\' You', abbreviation: '', length: 4.7)
Song.create(name: 'Luxury Liner', abbreviation: '', length: 8.5)
Song.create(name: 'Magic Foot', abbreviation: '', length: 3.6)
Song.create(name: 'Mess', abbreviation: '', length: 15)
Song.create(name: 'Midnight Special', abbreviation: '', length: 7.9)
Song.create(name: 'Mighty River', abbreviation: '', length: 7.5)
Song.create(name: 'Mission Man', abbreviation: '', length: 11.6)
Song.create(name: 'Mississippi Half Step', abbreviation: '', length: 9.7)
Song.create(name: 'Monkey', abbreviation: '', length: 4.1)
Song.create(name: 'Moonshiner', abbreviation: '', length: 6.5)
Song.create(name: 'Mountain Time', abbreviation: '', length: 9.2)
Song.create(name: 'Mourning Flies', abbreviation: '', length: 9.8)
Song.create(name: 'My Sisters and Brothers', abbreviation: '', length: 8.8)
Song.create(name: 'Neath the Stars', abbreviation: '', length: 4.5)
Song.create(name: 'New Camptown Races', abbreviation: '', length: 4.7)
Song.create(name: 'New Lee Highway Blues', abbreviation: '', length: 6.8)
Song.create(name: 'Old Dangerfield', abbreviation: '', length: 6.8)
Song.create(name: 'Old Man and the Land', abbreviation: '', length: 6.9)
Song.create(name: 'On the Banks', abbreviation: '', length: 6)
Song.create(name: 'Only by the Light', abbreviation: '', length: 7)
Song.create(name: 'One More Night on the Road', abbreviation: '', length: 5.9)
Song.create(name: 'Pack a Day', abbreviation: '', length: 3.4)
Song.create(name: 'Peace on Earth', abbreviation: '', length: 3.4)
Song.create(name: 'Peggy-O', abbreviation: '', length: 8)
Song.create(name: 'Potter\'s Feild', abbreviation: '', length: 6.3)
Song.create(name: 'Powderfinger', abbreviation: '', length: 9.4)
Song.create(name: 'Ragtime Annie Lee', abbreviation: '', length: 6)
Song.create(name: 'Railroad Earth', abbreviation: '', length: 6.5)
Song.create(name: 'Raindance', abbreviation: '', length: 6.4)
Song.create(name: 'Raven\'s Child', abbreviation: '', length: 6)
Song.create(name: 'Real Love', abbreviation: '', length: 5.6)
Song.create(name: 'Reuben\'s Train', abbreviation: '', length: 7.3)
Song.create(name: 'Right in Tune', abbreviation: '', length: 5)
Song.create(name: 'Roadhouse Blues', abbreviation: '', length: 8.4)
Song.create(name: 'RV', abbreviation: 'RV', length: 5.4)
Song.create(name: 'Saddle of the Sun', abbreviation: '', length: 5.2)
Song.create(name: 'Said What you Mean', abbreviation: '', length: 6.6)
Song.create(name: 'Seven Story Mountain', abbreviation: '', length: 14.4)
Song.create(name: 'Shockenawe Mountain', abbreviation: '', length: 2.8)
Song.create(name: 'Sing for Me', abbreviation: '', length: 5.3)
Song.create(name: 'Son of Mr. Green Genes', abbreviation: '', length: 4.4)
Song.create(name: 'Son of Sam', abbreviation: '', length: 5.4)
Song.create(name: 'Soul of a Man', abbreviation: '', length: 5.2)
Song.create(name: 'Spring-heeled Jack', abbreviation: '', length: 14)
Song.create(name: 'Standing on the Corner', abbreviation: '', length: 9.6)
Song.create(name: 'Still Water Get Away', abbreviation: '', length: 9.1)
Song.create(name: 'Storms', abbreviation: '', length: 6.4)
Song.create(name: 'Take a Bow', abbreviation: '', length: 7)
Song.create(name: 'Take Good Care of Yourself', abbreviation: '', length: 4.9)
Song.create(name: 'Take the Skinheads Bowling', abbreviation: '', length: 6.4)
Song.create(name: 'Terripin Station', abbreviation: '', length: 12.7)
Song.create(name: 'Through the Gates', abbreviation: '', length: 2.1)
Song.create(name: 'Too Much Information', abbreviation: '', length: 5.9)
Song.create(name: 'Tore Up Over You', abbreviation: '', length: 6.8)
Song.create(name: 'Tuba Mirum', abbreviation: '', length: 7.1)
Song.create(name: 'Walk Beside Me', abbreviation: '', length: 6.5)
Song.create(name: 'Walls of Time', abbreviation: '', length: 8.4)
Song.create(name: 'Warhead Boogie', abbreviation: '', length: 12.5)
Song.create(name: 'Waterfountain Quicksand', abbreviation: '', length: 4.5)
Song.create(name: 'Wavin\' Willy', abbreviation: '', length: 4.6)
Song.create(name: 'Wayfaring Stranger', abbreviation: '', length: 7.2)
Song.create(name: 'Wheel, The', abbreviation: '', length: 10.8)
Song.create(name: 'When the Sun Gets in Your Blood', abbreviation: '', length: 7.4)
Song.create(name: 'Where Songs Begin', abbreviation: '', length: 8.1)
Song.create(name: 'Working on a Building', abbreviation: '', length: 5.3)
Song.create(name: 'Woyia Minor Key', abbreviation: '', length: 5.3)
Song.create(name: 'You Never Know', abbreviation: '', length: 6.9)

